export const theme = {
  normal: {
    buttonBackground: "#008080",
    sectionBackground: "#fff",
    shadow: "#ccc",
    background: "#eee",
    transparent: "transparent",
    check: "#008000",
    remove: "#FF0000",
    edit: "#FFA500",
    outline: "#000",
    interactionButtonText: "#fff",
    text: "#000",
  },
  dark: {
    buttonBackground: "#8DB9B9",
    sectionBackground: "#3C4453",
    shadow: "#000",
    background: "#272A30",
    transparent: "transparent",
    check: "#008000",
    remove: "#FF0000",
    edit: "#FFA500",
    outline: "#808080	",
    interactionButtonText: "#fff",
    text: "#EBEDEF",
  },
};
